# -*- coding: utf-8 -*-
"""Termal Process Versi 1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWV-2N-qrRYPWvXThmelkJ_cKzruSDKl
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from openpyxl import load_workbook
from openpyxl.drawing.image import Image

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from openpyxl import load_workbook
from openpyxl.drawing.image import Image

st.title("Thermal Process Analyzer")

uploaded_file = st.file_uploader(
    "Upload CSV",
    type=["csv"]
)

if uploaded_file is None:
    st.stop()

data = pd.read_csv(uploaded_file)

loggers = data.columns[1:]

# ==========================
# HITUNG F0 SEMUA LOGGER
# ==========================

hasil_f0 = []

for logger in loggers:
    
    suhu_C = (
        (data[logger] - 32)
        * 5 / 9
    )

    LR = 10 ** (
        (suhu_C - 121.1)
        / 10
    )

    letalitas = (
        (
            data["Waktu"]
            - data["Waktu"].shift(1)
        )
        *
        (
            (
                LR
                + LR.shift(1)
            ) / 2
        )
    ).fillna(0)

    F0 = letalitas.sum()

    hasil_f0.append([
        logger,
        F0,
        data[logger].max(),
        data[logger].min()
    ])



# ==========================
# TABEL F0 LOGGER
# ==========================

summary_logger = pd.DataFrame(
    hasil_f0,
    columns=[
        "Logger",
        "F0",
        "Tmax",
        "Tmin"
    ]
)

summary_logger = summary_logger.sort_values(
    "F0"
)


# ==========================
# COLD SPOT
# ==========================

cold_logger = summary_logger.iloc[0]["Logger"]

cold_f0 = summary_logger.iloc[0]["F0"]


# ==========================
# HOT SPOT
# ==========================

hot_logger = summary_logger.iloc[-1]["Logger"]

hot_f0 = summary_logger.iloc[-1]["F0"]


# ==========================
# DATA COLD SPOT
# ==========================

cold_data = pd.DataFrame()

cold_data["Waktu"] = data["Waktu"]

cold_data["suhu_F"] = data[cold_logger]

cold_data["suhu_C"] = (
    (cold_data["suhu_F"] - 32)
    * 5 / 9
)

cold_data["LR"] = (
    10 ** (
        (
            cold_data["suhu_C"]
            - 121.1
        )
        / 10
    )
)

cold_data["letalitas"] = (
    (
        cold_data["Waktu"]
        - cold_data["Waktu"].shift(1)
    )
    *
    (
        (
            cold_data["LR"]
            + cold_data["LR"].shift(1)
        )
        / 2
    )
).fillna(0)

cold_data["F0_kumulatif"] = (
    cold_data["letalitas"]
    .cumsum()
)


# ==========================
# SUMMARY
# ==========================

summary = pd.DataFrame({

    "Parameter":[

        "Jumlah Logger",

        "Cold Spot",

        "F0 Cold Spot",

        "Hot Spot",

        "F0 Hot Spot",

        "F0 Total"

    ],

    "Nilai":[

        len(loggers),

        cold_logger,

        round(cold_f0,2),

        hot_logger,

        round(hot_f0,2),

        round(
            cold_data["F0_kumulatif"]
            .iloc[-1],
            2
        )

    ]
})


# ==========================
# GRAFIK SUHU
# ==========================

plt.figure(figsize=(10,5))

plt.plot(
    cold_data["Waktu"],
    cold_data["suhu_F"]
)

plt.title(
    f"Cold Spot {cold_logger}"
)

plt.xlabel("Waktu")

plt.ylabel("Suhu F")

plt.grid()

plt.savefig(
    "kurva_suhu.png"
)

plt.close()


# ==========================
# GRAFIK F0
# ==========================

plt.figure(figsize=(10,5))

plt.plot(
    cold_data["Waktu"],
    cold_data["F0_kumulatif"]
)

plt.title(
    "F0 Kumulatif"
)

plt.xlabel("Waktu")

plt.ylabel("F0")

plt.grid()

plt.savefig(
    "kurva_f0.png"
)

plt.close()


# ==========================
# EXCEL
# ==========================

excel_file = "Laporan_Retort.xlsx"

with pd.ExcelWriter(
    excel_file,
    engine="openpyxl"
) as writer:

    summary.to_excel(
        writer,
        sheet_name="Summary",
        index=False
    )

    summary_logger.to_excel(
        writer,
        sheet_name="F0 Logger",
        index=False
    )

    cold_data.to_excel(
        writer,
        sheet_name="Data Retort",
        index=False
    )


# ==========================
# TAMBAH GAMBAR
# ==========================

wb = load_workbook(
    excel_file
)

ws = wb.create_sheet(
    "Kurva"
)

ws.add_image(
    Image("kurva_suhu.png"),
    "A1"
)

ws.add_image(
    Image("kurva_f0.png"),
    "A30"
)

wb.save(
    excel_file
)

print(
    "Laporan selesai dibuat"
)

st.pyplot(plt.gcf())
for logger in loggers:
    plt.plot(data["Waktu"], data[logger], label=logger)

plt.title("Grafik Suhu Lengkap Semua Logger")
plt.xlabel("Waktu")
plt.ylabel("Suhu (F)")
plt.grid(True)
plt.legend(loc='upper left', bbox_to_anchor=(1, 1)) # Place legend outside the plot area
plt.tight_layout(rect=[0, 0, 0.85, 1]) # Adjust layout to prevent legend overlap
plt.savefig("kurva_suhu_lengkap.png")
plt.close()

print("Grafik suhu lengkap berhasil dibuat.")

wb = load_workbook(excel_file)
ws_full_temp = wb.create_sheet("Suhu Lengkap")
ws_full_temp.add_image(Image("kurva_suhu_lengkap.png"), "A1")
wb.save(excel_file)
print("Grafik suhu lengkap ditambahkan ke laporan Excel.")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 7))
for logger in loggers:

    plt.plot(
        data["Waktu"],
        data[logger],
        label=logger
    )

plt.xlabel("Waktu")
plt.ylabel("Suhu (°F)")
plt.legend()
plt.grid()

plt.show()

with open(
    "Laporan_Retort.xlsx",
    "rb"
) as f:

    st.download_button(
        "Download Laporan",
        f,
        file_name="Laporan_Retort.xlsx"
    )
